In [5]:
from numpy import *
data=array([[1,2],[2,3]])
print(data)

[[1 2]
 [2 3]]


In [6]:
#order of the matrix
data.shape

(2, 2)

In [9]:
#zero matrix of order 10x4
zero_matrix=zeros((10,4))
print(zero_matrix)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [10]:
#ones matrix of order 10x4
one_matrix=ones((10,4))
print(one_matrix)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [12]:
#random matrix of integers in range[0,9] with order 5x5
rand_matrix=random.randint(10,size=(5,5))
print(rand_matrix)

[[5 7 8 3 7]
 [6 0 1 6 4]
 [8 3 5 9 5]
 [3 9 9 3 2]
 [0 0 2 8 8]]


In [14]:
#column vector of random integers in range [0,9] with order 5x1
col_vector=random.randint(10,size=(5,1))
print(col_vector)

[[7]
 [0]
 [2]
 [8]
 [0]]


In [16]:
#print element at index 1 of column vector
print(col_vector[1])

[0]


In [17]:
#print first element of random matrix
print(rand_matrix[0,0])

5


In [18]:
#print the first column
print(rand_matrix[:,0:1])

[[5]
 [6]
 [8]
 [3]
 [0]]


In [19]:
#print the first row
print(rand_matrix[0:1,:])

[[5 7 8 3 7]]


In [20]:
#print second row
print(rand_matrix[1:2,:])

[[6 0 1 6 4]]


In [22]:
#print c1,c2,c3 of rows 0 ans 1
cols=array([[1,2,3]])
print(rand_matrix[0:2,cols])

[[[7 8 3]]

 [[0 1 6]]]


In [23]:
#convert from 2d array to 1d array
flattened=rand_matrix.flatten()
print(flattened)

[5 7 8 3 7 6 0 1 6 4 8 3 5 9 5 3 9 9 3 2 0 0 2 8 8]


In [24]:
rand_matrix2=random.randint(10,size=(5,5))
print(rand_matrix2)

[[6 5 3 9 5]
 [5 9 2 7 8]
 [3 9 3 1 6]
 [1 7 6 2 2]
 [6 3 1 5 4]]


In [25]:
#dot product of matrix
dot_product=rand_matrix.dot(rand_matrix2)
print(dot_product)

[[134 202  78 143 163]
 [ 69  93  61  87  64]
 [117 190 104 141 132]
 [105 204  74 115 155]
 [ 62  98  62  58  60]]
