In [1]:
from numpy import *

In [2]:
num_movies = 10
num_users = 5

In [3]:
ratings = random.randint(11, size = (num_movies, num_users))




print (ratings)

[[ 5  6  5  9  0]
 [ 7  4  7  9  3]
 [ 3  9  9  6  8]
 [10  1  0  5  5]
 [ 3  7  7  1  8]
 [ 7  2  8  3  4]
 [ 7  6  7  1  8]
 [ 4  8  4  9  2]
 [ 6  8  5 10  0]
 [10  0 10  0  7]]


In [4]:
did_rate = (ratings != 0) * 1




print (did_rate)

[[1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 0]
 [1 0 1 0 1]]


In [5]:
print (ratings != 0)


[[ True  True  True  True False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True False  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True False]
 [ True False  True False  True]]


In [7]:
ratings.shape



(10, 5)

In [8]:


did_rate.shape

(10, 5)

In [10]:
nikhil_ratings = zeros((num_movies, 1))
print (nikhil_ratings)


[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]


In [11]:
nikhil_ratings[0] = 8
nikhil_ratings[4] = 7
nikhil_ratings[7] = 3

print (nikhil_ratings)

[[ 8.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 7.]
 [ 0.]
 [ 0.]
 [ 3.]
 [ 0.]
 [ 0.]]


In [13]:
ratings = append(nikhil_ratings, ratings, axis = 1)
did_rate = append(((nikhil_ratings != 0) * 1), did_rate, axis = 1)

print(ratings)


[[  8.   5.   6.   5.   9.   0.]
 [  0.   7.   4.   7.   9.   3.]
 [  0.   3.   9.   9.   6.   8.]
 [  0.  10.   1.   0.   5.   5.]
 [  7.   3.   7.   7.   1.   8.]
 [  0.   7.   2.   8.   3.   4.]
 [  0.   7.   6.   7.   1.   8.]
 [  3.   4.   8.   4.   9.   2.]
 [  0.   6.   8.   5.  10.   0.]
 [  0.  10.   0.  10.   0.   7.]]


In [14]:
ratings.shape


(10, 6)

In [15]:
print (did_rate)

[[1 1 1 1 1 0]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 0 1 1]
 [1 1 1 1 1 1]
 [0 1 1 1 1 1]
 [0 1 1 1 1 1]
 [1 1 1 1 1 1]
 [0 1 1 1 1 0]
 [0 1 0 1 0 1]]


In [16]:
did_rate.shape


(10, 6)

In [18]:
def normalize_ratings(ratings, did_rate):
    num_movies = ratings.shape[0]
    
    ratings_mean = zeros(shape = (num_movies, 1))
    ratings_norm = zeros(shape = ratings.shape)
    
    for i in range(num_movies): 
        # Get all the indexes where there is a 1
        idx = where(did_rate[i] == 1)[0]
        #  Calculate mean rating of ith movie only from user's that gave a rating
        ratings_mean[i] = mean(ratings[i, idx])
        ratings_norm[i, idx] = ratings[i, idx] - ratings_mean[i]
    
    return ratings_norm, ratings_mean

In [19]:
ratings, ratings_mean = normalize_ratings(ratings, did_rate)

In [20]:
num_users = ratings.shape[1]
num_features = 3

In [22]:
X = array([[1, 2], [1, 5], [1, 9]])
Theta = array([[0.23], [0.34]])



print (X)




print (Theta)



Y = X.dot(Theta)
print (Y)

[[1 2]
 [1 5]
 [1 9]]
[[ 0.23]
 [ 0.34]]
[[ 0.91]
 [ 1.93]
 [ 3.29]]


In [23]:
movie_features = random.randn( num_movies, num_features )
user_prefs = random.randn( num_users, num_features )
initial_X_and_theta = r_[movie_features.T.flatten(), user_prefs.T.flatten()]

In [25]:
print( movie_features)

[[ 1.74554414 -1.9041309  -0.33525391]
 [-1.00008694 -0.0758113  -0.95930623]
 [ 0.39202215 -0.61353475  0.21972597]
 [ 0.4178501  -1.829534    0.8496629 ]
 [ 1.17681095  1.79541829  0.63696113]
 [ 1.33543908  1.50566234 -0.02394895]
 [-0.09524814  0.82210359  1.76334716]
 [ 0.20144111  0.25176678 -0.80813968]
 [ 0.91121401 -0.00485061  1.13317495]
 [ 0.70507103 -0.49508446 -0.32262471]]


In [26]:
print (user_prefs)


[[-0.07277566  0.03457819  1.25446789]
 [-0.26365453 -1.15036402  0.32573323]
 [ 0.52025037  1.79183399  2.01226529]
 [-0.29193796 -1.61345395  0.03366627]
 [ 0.5998965  -0.67544792 -0.31141588]
 [-1.3460922   0.38111134 -0.21163814]]


In [28]:
print (initial_X_and_theta)

[ 1.74554414 -1.00008694  0.39202215  0.4178501   1.17681095  1.33543908
 -0.09524814  0.20144111  0.91121401  0.70507103 -1.9041309  -0.0758113
 -0.61353475 -1.829534    1.79541829  1.50566234  0.82210359  0.25176678
 -0.00485061 -0.49508446 -0.33525391 -0.95930623  0.21972597  0.8496629
  0.63696113 -0.02394895  1.76334716 -0.80813968  1.13317495 -0.32262471
 -0.07277566 -0.26365453  0.52025037 -0.29193796  0.5998965  -1.3460922
  0.03457819 -1.15036402  1.79183399 -1.61345395 -0.67544792  0.38111134
  1.25446789  0.32573323  2.01226529  0.03366627 -0.31141588 -0.21163814]


In [29]:
initial_X_and_theta.shape

(48,)

In [30]:
movie_features.T.flatten().shape

(30,)

In [31]:
user_prefs.T.flatten().shape

(18,)

In [32]:
initial_X_and_theta


array([ 1.74554414, -1.00008694,  0.39202215,  0.4178501 ,  1.17681095,
        1.33543908, -0.09524814,  0.20144111,  0.91121401,  0.70507103,
       -1.9041309 , -0.0758113 , -0.61353475, -1.829534  ,  1.79541829,
        1.50566234,  0.82210359,  0.25176678, -0.00485061, -0.49508446,
       -0.33525391, -0.95930623,  0.21972597,  0.8496629 ,  0.63696113,
       -0.02394895,  1.76334716, -0.80813968,  1.13317495, -0.32262471,
       -0.07277566, -0.26365453,  0.52025037, -0.29193796,  0.5998965 ,
       -1.3460922 ,  0.03457819, -1.15036402,  1.79183399, -1.61345395,
       -0.67544792,  0.38111134,  1.25446789,  0.32573323,  2.01226529,
        0.03366627, -0.31141588, -0.21163814])

In [34]:
def unroll_params(X_and_theta, num_users, num_movies, num_features):
    # Retrieve the X and theta matrixes from X_and_theta, based on their dimensions (num_features, num_movies, num_movies)
    # --------------------------------------------------------------------------------------------------------------
    # Get the first 30 (10 * 3) rows in the 48 X 1 column vector
    first_30 = X_and_theta[:num_movies * num_features]
    # Reshape this column vector into a 10 X 3 matrix
    X = first_30.reshape((num_features, num_movies)).transpose()
    # Get the rest of the 18 the numbers, after the first 30
    last_18 = X_and_theta[num_movies * num_features:]
    # Reshape this column vector into a 6 X 3 matrix
    theta = last_18.reshape(num_features, num_users ).transpose()
    return X, theta

In [35]:
def calculate_gradient(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
    X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)
    
    # we multiply by did_rate because we only want to consider observations for which a rating was given
    difference = X.dot( theta.T ) * did_rate - ratings
    X_grad = difference.dot( theta ) + reg_param * X
    theta_grad = difference.T.dot( X ) + reg_param * theta
    
    # wrap the gradients back into a column vector 
    return r_[X_grad.T.flatten(), theta_grad.T.flatten()]

In [36]:
def calculate_cost(X_and_theta, ratings, did_rate, num_users, num_movies, num_features, reg_param):
    X, theta = unroll_params(X_and_theta, num_users, num_movies, num_features)

    # we multiply (element-wise) by did_rate because we only want to consider observations for which a rating was given
    cost = sum( (X.dot( theta.T ) * did_rate - ratings) ** 2 ) / 2
    # '**' means an element-wise power
    regularization = (reg_param / 2) * (sum( theta**2 ) + sum(X**2))
    return cost + regularization

In [37]:
from scipy import optimize




reg_param = 30


In [38]:
minimized_cost_and_optimal_params = optimize.fmin_cg(calculate_cost, fprime=calculate_gradient, x0=initial_X_and_theta,
                                                     args=(ratings, did_rate, num_users, num_movies, num_features, reg_param), 
                                                     maxiter=100, disp=True, full_output=True ) 




Optimization terminated successfully.
         Current function value: 130.900000
         Iterations: 11
         Function evaluations: 22
         Gradient evaluations: 22


In [39]:
cost, optimal_movie_features_and_user_prefs = minimized_cost_and_optimal_params[1], minimized_cost_and_optimal_params[0]



In [40]:
movie_features, user_prefs = unroll_params(optimal_movie_features_and_user_prefs, num_users, num_movies, num_features)
