In [1]:
from numpy import *

In [5]:
num_users=5
num_movies=5
movie_user=random.randint(6,size=(num_users,num_movies))

In [6]:
print(movie_user)

[[2 3 0 4 2]
 [2 5 1 4 3]
 [2 3 0 1 5]
 [5 1 0 4 2]
 [3 5 5 2 5]]


In [7]:
did_rate=movie_user!=0

In [8]:
print(did_rate)

[[ True  True False  True  True]
 [ True  True  True  True  True]
 [ True  True False  True  True]
 [ True  True False  True  True]
 [ True  True  True  True  True]]


In [9]:
did_rate=did_rate*1

In [10]:
print(did_rate)

[[1 1 0 1 1]
 [1 1 1 1 1]
 [1 1 0 1 1]
 [1 1 0 1 1]
 [1 1 1 1 1]]


In [11]:
user0=movie_user[:,0:1]

In [12]:
print(user0)

[[2]
 [2]
 [2]
 [5]
 [3]]


In [16]:
user1=movie_user[:,1:2]

In [17]:
print(user1)

[[3]
 [5]
 [3]
 [1]
 [5]]


In [18]:
user0-user1

array([[-1],
       [-3],
       [-1],
       [ 4],
       [-2]])

In [20]:
sq=(user0-user1)**2

In [21]:
print(sq)

[[ 1]
 [ 9]
 [ 1]
 [16]
 [ 4]]


In [22]:
sim=(sum(sq))

In [24]:
print(sim**(1/2))

5.56776436283


In [29]:
user0=movie_user[:,0:1]

In [28]:
print(user1)

[[3]
 [5]
 [3]
 [1]
 [5]]


In [52]:
user2=movie_user[:,2:3]

In [53]:
print(user2)

[[0]
 [1]
 [0]
 [0]
 [5]]


In [40]:
user3=movie_user[:,3:4]

In [41]:
print(user3)

[[4]
 [4]
 [1]
 [4]
 [2]]


In [43]:
user4=movie_user[:,4:5]

In [44]:
print(user4)

[[2]
 [3]
 [5]
 [2]
 [5]]


In [51]:
user1=movie_user[:,1:2]
print(user1)

[[3]
 [5]
 [3]
 [1]
 [5]]


In [59]:
#eucladien distance

In [54]:
user01=(sum((user0-user1)**2))**(1/2)

In [88]:
print(user01
     )

5.56776436283


In [86]:
user02=(sum((user0-user2)**2))**(1/2)

In [87]:
print(user02)

6.16441400297


In [84]:
user03=(sum((user0-user3)**2))**(1/2)
print(user03)

3.31662479036


In [85]:
user04=(sum((user0-user4)**2))**(1/2)
print(user04)

4.79583152331


In [89]:
#eucladien distance between user 0 and user 3 is minimum so they are most closest or most similar 

In [58]:
#cosine similarity

In [60]:
print(user0)

[[2]
 [2]
 [2]
 [5]
 [3]]


In [61]:
print(user1)

[[3]
 [5]
 [3]
 [1]
 [5]]


In [62]:
user0*user1

array([[ 6],
       [10],
       [ 6],
       [ 5],
       [15]])

In [63]:
moduser0=(sum(user0**2))**(1/2)

In [64]:
print(moduser0)

6.78232998313


In [65]:
moduser1=(sum(user1**2))**(1/2)

In [66]:
moduser2=(sum(user2**2))**(1/2)

In [67]:
moduser3=(sum(user3**2))**(1/2)

In [68]:
moduser4=(sum(user4**2))**(1/2)

In [77]:
cos01=(sum((user0*user1)))/(moduser0*moduser1)

In [78]:
print(cos01)

0.745496878238


In [81]:
cos02=(sum((user0*user2)))/(moduser0*moduser2)
print(cos02)

0.491567692171


In [82]:
cos03=(sum((user0*user3)))/(moduser0*moduser3)
print(cos03)

0.891119250874


In [83]:
cos04=(sum((user0*user4)))/(moduser0*moduser4)
print(cos04)

0.810580583621


In [90]:
#cos0=1, here user 0 and user 3 have greatest cos value thus the angle between then is minimum thus they are similar


In [ ]:
#both eucladien and cosine similarity shows that user 0 and user 3 are m